apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-api
  template:
    metadata:
      labels:
        app: standalone-api
    spec:
      containers:
      - name: python-api
        image: image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8
        command: ["python3", "/mnt/app.py"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: script-vol
          mountPath: /mnt
      volumes:
      - name: script-vol
        configMap:
          name: api-script
---
apiVersion: v1
kind: Service
metadata:
  name: standalone-api
spec:
  selector:
    app: standalone-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: standalone-api
spec:
  to:
    kind: Service
    name: standalone-api
  port:
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-script
data:
  app.py: |
    from http.server import HTTPServer, BaseHTTPRequestHandler
    import json

    class SwaggerHandler(BaseHTTPRequestHandler):
        def do_OPTIONS(self):
            self.send_response(200)
            self.send_header('Access-Control-Allow-Origin', '*')
            self.send_header('Access-Control-Allow-Methods', 'GET, OPTIONS')
            self.send_header('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type')
            self.end_headers()

        def do_GET(self):
            if self.path == "/openapi.json":
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                spec = {
                    "openapi": "3.0.0",
                    "info": {"title": "Fixed CORS API", "version": "1.0.0"},
                    "paths": {
                        "/hello": {
                            "get": {
                                "summary": "Test Connectivity",
                                "responses": {"200": {"description": "Success"}}
                            }
                        }
                    }
                }
                self.wfile.write(json.dumps(spec).encode())
            
            elif self.path == "/hello":
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(b'{"message": "Hello from the standalone pod!"}')

    print("API starting on port 8080...")
    HTTPServer(('0.0.0.0', 8080), SwaggerHandler).serve_forever()
